name: Build and Deploy

on:
  push:
    branches:
      - main  # 或者你想要触发构建的分支
permissions:
  contents: write  # 必须显式赋予写权限，默认是 read-only
  pull-requests: read


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 或者你选择的任何其他运行环境

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build for production
        run: pnpm docs:build


      - name: Deploy to GitHub Pages  # 部署到GitHub Pages（如果需要）
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          force_orphan: true
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist  # 或者你的构建输出目录，例如dist或public